function prepare_slider(sliderID,leftBut,rightBut){var x_pos=0;var li_items_n=0;var right_clicks=0;var left_clicks=0;var li_col=jQuery(sliderID).children("li");var li_width=li_col.outerWidth(true);var viewWindow=1
li_col.each(function(index){x_pos+=jQuery(this).outerWidth(true);li_items_n++;})
right_clicks=li_items_n- viewWindow;total_clicks=li_items_n- viewWindow;jQuery(sliderID).css('position','relative');jQuery(sliderID).css('left','0px');jQuery(sliderID).css('width',x_pos+'px');var is_playing=false;var completed=function(){is_playing=false;}
jQuery(leftBut).click(function(){cur_offset=jQuery(sliderID).position().left;if(!is_playing){if(left_clicks>0){is_playing=true;jQuery(sliderID).animate({'left':cur_offset+ li_width+'px'},700,"linear",completed);right_clicks++;left_clicks--;}
else{is_playing=true;jQuery(sliderID).animate({'left':-li_width*total_clicks+'px'},700,"linear",completed);right_clicks=0;left_clicks=total_clicks;}}});jQuery(rightBut).click(function(){if(!is_playing){cur_offset=jQuery(sliderID).position().left;if(right_clicks>0){is_playing=true;jQuery(sliderID).animate({'left':cur_offset- li_width+'px'},700,"linear",completed);right_clicks--;left_clicks++;}
else{is_playing=true;jQuery(sliderID).animate({'left':0+'px'},700,"linear",completed);left_clicks=0;right_clicks=total_clicks;}}});}
function prepare_slider2(sliderID2,leftBut2,rightBut2){var x_pos2=0;var li_items_n2=1;var right_clicks2=0;var left_clicks2=0;var li_col2=jQuery(sliderID2).children("li");var li_width2=li_col2.outerWidth(true);var viewWindow2=Math.round(jQuery('.box-top').width()/li_width2);li_col2.each(function(index){x_pos2+=jQuery(this).outerWidth(true);li_items_n2++;})
right_clicks2=li_items_n2- viewWindow2;total_clicks2=li_items_n2- viewWindow2;jQuery(sliderID2).css('position','relative');jQuery(sliderID2).css('left','0px');jQuery(sliderID2).css('width',x_pos2+'px');var is_playing=false;var completed=function(){is_playing=false;}
jQuery(leftBut2).click(function(){cur_offset=jQuery(sliderID2).position().left;if(!is_playing){if(left_clicks2>0){is_playing=true;jQuery(sliderID2).animate({'left':cur_offset+ li_width2+'px'},700,"linear",completed);right_clicks2++;left_clicks2--;}
else{is_playing=true;jQuery(sliderID2).animate({'left':-li_width2*total_clicks2+'px'},700,"linear",completed);right_clicks2=0;left_clicks2=total_clicks2;}}});jQuery(rightBut2).click(function(){if(!is_playing){cur_offset=jQuery(sliderID2).position().left;if(right_clicks2>0){is_playing=true;jQuery(sliderID2).animate({'left':cur_offset- li_width2+'px'},700,"linear",completed);right_clicks2--;left_clicks2++;}
else{is_playing=true;jQuery(sliderID2).animate({'left':0+'px'},700,"linear",completed);left_clicks2=0;right_clicks2=total_clicks2;}}});}
function intro(){var slider_link=jQuery('#right_but');var slider_link_index=1;var slider_count=jQuery('#slider_list > li').size();function slider_intro(){if(slider_link_index<=slider_count){slider_link.trigger('click');slider_link_index++;setTimeout(function(){slider_intro()},7000);}}
setTimeout(function(){slider_intro()},7000)}
function intro2(){var slider_link=jQuery('#right_but_2');var slider_link_index=4;var slider_count=jQuery('#slider_list_2 > li').size();function slider_intro(){if(slider_link_index<=slider_count){slider_link.trigger('click');slider_link_index++;setTimeout(function(){slider_intro()},7000);}}
setTimeout(function(){slider_intro()},7000)}
;
